- title: Slice level data leakage
  group: featured
  image: https://media.springernature.com/full/springer-static/image/art%3A10.1038%2Fs41598-021-01681-w/MediaObjects/41598_2021_1681_Fig2_HTML.png?as=webp
  link: https://www.nature.com/articles/s41598-021-01681-w#Fig2
  description: Slice level data leakage
  repo: Imaging-AI-for-Health-virtual-lab/Slice-Level-Data-Leakage

