- id: https://doi.org/10.1038/s41598-021-01681-w
  image: https://github.com/riccardoscheda/riccardoscheda.github.io/blob/main/images/slice-level-data-leakage.png?raw=true
  repo: Imaging-AI-for-Health-virtual-lab/Slice-Level-Data-Leakage

